
AUDIO_ENTRY(0, MUSIC_GROUP, BACKGROUND_MUSIC, "Sounds/test.wav")
AUDIO_ENTRY(1, EFFECTS_GROUP, PLAYER_JUMP, "Sounds/jump.wav")
AUDIO_ENTRY(2, EFFECTS_GROUP, PLAYER_RUN, "Sounds/gravel_run.wav")
AUDIO_ENTRY(3, EFFECTS_GROUP, BUTTON_HOVER, "Sounds/button_hover.wav")
AUDIO_ENTRY(4, EFFECTS_GROUP, BUTTON_PRESSED, "Sounds/button_press.wav")
AUDIO_ENTRY(5, EFFECTS_GROUP, PROJECTILE_EXPLOSION, "Sounds/explosion0.wav")